#!/usr/bin/env bash

find . -type f -name "*.od*" | while read -r i ; do
   [ "$1" ] || { echo "You forgot search string!" ; exit 1 ; }
   if unzip -ca "$i" 2>/dev/null | grep -iq "$*" ; then
      echo "String found in $i" | nl
   fi
done
